# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: CCSDS MO
email: moims-sc@mailman.ccsds.org
description: >- # this means to ignore newlines until "baseurl:"
    CCSDS MO is defining a service oriented architecture consisting of set of <strong>standard services</strong>. It provides interoperability with partner system and infrastructure, reduces the risk of space missions by reusing systems and operational concepts, and facilitate the development of generic on-board and on ground software that can be shared by multiple missions.
baseurl: ""
url: "" # the base hostname & protocol for your site, e.g. http://example.com

button1:
  name: CCSDS Website
  url: https://public.ccsds.org

button2:
  name: CCSDS MO
  url: https://cwe.ccsds.org/moims/default.aspx

plugins:
  - jekyll-toc
# Build settings
markdown: kramdown
highlighter: rouge

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
